version: 2
updates:
  # pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "eth-offline-signer-maintainers"
    assignees:
      - "eth-offline-signer-maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates
    groups:
      production-dependencies:
        patterns:
          - "commander"
          - "viem"
          - "zod"
      development-dependencies:
        patterns:
          - "@types/*"
          - "@biomejs/*"
          - "@vitest/*"
          - "typescript"
          - "tsup"
          - "vitest"
          - "husky"
          - "execa"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"