name: 'Setup Node.js and pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with caching'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '18'
  pnpm-version:
    description: 'pnpm version to use'
    required: false
    default: '9'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Get pnpm store directory
      id: pnpm-store-path
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store-path.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: |
        if [ -f "pnpm-lock.yaml" ]; then
          echo "Found pnpm-lock.yaml, attempting frozen lockfile install..."
          if ! pnpm install --frozen-lockfile; then
            echo "Frozen lockfile install failed, falling back to regular install..."
            echo "This may happen when package.json was updated but pnpm-lock.yaml wasn't committed."
            pnpm install
          fi
        else
          echo "No pnpm-lock.yaml found, installing without frozen lockfile..."
          pnpm install --no-frozen-lockfile
        fi